wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.6
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1725982273.0
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 3
      - 8
      - 23
      - 37
      - 62
      4: 3.10.13
      5: 0.16.6
      8:
      - 3
      - 5
      10:
      - 9
      13: windows-amd64
dataset:
  desc: null
  value: infrared_thermal_feet
model:
  desc: null
  value: f_b
