wandb_version: 1

dataset:
  desc: null
  value: infrared_thermal_feet
model:
  desc: null
  value: f_b
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.16.0
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1727369357.114966
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      3:
      - 23
      4: 3.10.14
      5: 0.16.0
      8:
      - 3
      - 5
      13: windows-amd64
